[2025-04-01 00:09:14] [ERROR]: ❌ Error during Gemini API request | Meta: {"retriesLeft":3}
Stack Trace:
AxiosError: Request failed with status code 401
    at settle (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:2031:12)
    at Unzip.handleStreamEnd (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:3148:11)
    at Unzip.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at Axios.request (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:4258:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchGeminiResponse (E:\documenten\discord\Bots\Main bots\Milena\index.js:197:28)
    at async testGeminiAPI (E:\documenten\discord\Bots\Main bots\Milena\index.js:220:26)
    at async Client.<anonymous> (E:\documenten\discord\Bots\Main bots\Milena\index.js:253:5)
[2025-04-01 00:09:14] [ERROR]: Gemini API Test Error
Stack Trace:
AxiosError: Request failed with status code 401
    at settle (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:2031:12)
    at Unzip.handleStreamEnd (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:3148:11)
    at Unzip.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at Axios.request (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:4258:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchGeminiResponse (E:\documenten\discord\Bots\Main bots\Milena\index.js:197:28)
    at async testGeminiAPI (E:\documenten\discord\Bots\Main bots\Milena\index.js:220:26)
    at async Client.<anonymous> (E:\documenten\discord\Bots\Main bots\Milena\index.js:253:5)
[2025-04-01 00:16:33] [ERROR]: ❌ Error during Gemini API request | Meta: {"retriesLeft":3}
Stack Trace:
AxiosError: Request failed with status code 401
    at settle (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:2031:12)
    at Unzip.handleStreamEnd (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:3148:11)
    at Unzip.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at Axios.request (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:4258:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchGeminiResponse (E:\documenten\discord\Bots\Main bots\Milena\index.js:194:28)
    at async testGeminiAPI (E:\documenten\discord\Bots\Main bots\Milena\index.js:217:26)
    at async Client.<anonymous> (E:\documenten\discord\Bots\Main bots\Milena\index.js:250:5)
[2025-04-01 00:16:33] [ERROR]: Gemini API Test Error
Stack Trace:
AxiosError: Request failed with status code 401
    at settle (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:2031:12)
    at Unzip.handleStreamEnd (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:3148:11)
    at Unzip.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at Axios.request (E:\documenten\discord\Bots\Main bots\Milena\node_modules\axios\dist\node\axios.cjs:4258:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchGeminiResponse (E:\documenten\discord\Bots\Main bots\Milena\index.js:194:28)
    at async testGeminiAPI (E:\documenten\discord\Bots\Main bots\Milena\index.js:217:26)
    at async Client.<anonymous> (E:\documenten\discord\Bots\Main bots\Milena\index.js:250:5)
